// export { default as Navbar } from './Navbar/Navbar';
export { default as Signup } from './userAuth/signup/signup';
// export { default as Signup2 } from './userAuth/Signup/Signup2';
export { default as Login } from './userAuth/Login/Login2';
export { default as EnterOtp} from './enterotp/enterotp';
export { default as Dashboard } from './dashboard/dashboard';
export { default as ConfirmDialog } from './ConfirmDialog/ConfirmDialog';
export { default as Notification } from './Notification/Notifications';
export { default as Popup } from './Popup/Popup';
// export { default as Dashboard } from './Dashboard/Dashboard';
export { default as DatePickerField } from './Controls/Pickers/DatePicker';
// export { default as TimePickerField } from './Controls/Pickers/TimePicker';
export { default as DateTimePickerField } from './Controls/Pickers/DateTimePicker';
export { default as Prescription } from './Prescription/Prescription';