server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/HospitalManagementSystem
spring.datasource.username=root
spring.datasource.password=yG5(b)r#qgb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode = always
#debug=true
#Database Configuration
#
##provide jdbc url for the database
#spring.datasource.url=jdbc:mysql://localhost:3306/HospitalManagementSystem
##provide username and password
#spring.datasource.username=root
#spring.datasource.password=Aditya@871